server:
  port: ${DISCOVERY_SERVER_PORT}

spring:
  application:
    name: ${DISCOVERY_SERVER_NAME}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}