server:
  port: ${THESIS_SERVICE_PORT}

spring:
  application:
    name: ${THESIS_SERVICE_NAME}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:},optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:../../.env[.properties],optional:classpath:.env[.properties]
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI}
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST}
      retry:
        initial-interval: ${SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL}
        max-attempts: ${SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS}
        multiplier: ${SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER}
      label: ${SPRING_CLOUD_CONFIG_LABEL}

ai:
  gemini:
    api-key: ${AI_GEMINI_API_KEY}
    model-name: ${AI_GEMINI_MODEL_NAME}
