server:
  port: ${API_GATEWAY_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:true}
    key-store: ${SERVER_SSL_KEY_STORE:}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:}
    key-alias: ${SERVER_SSL_KEY_ALIAS:phenikaa}

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:../../.env[.properties],optional:classpath:.env[.properties]
  main:
    web-application-type: ${SPRING_MAIN_WEB_APPLICATION_TYPE}
  application:
    name: ${API_GATEWAY_NAME}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}
          lower-case-service-id: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID}

      routes:
        - id: ${AUTH_SERVICE_NAME}
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

        - id: ${USER_SERVICE_NAME}
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/user-service/student/**, /api/user-service/admin/**, /api/teacher/**, /internal/users/**

        - id: ${THESIS_SERVICE_NAME}
          uri: ${THESIS_SERVICE_URL}
          predicates:
            - Path=/api/thesis-service/teacher/**, /api/thesis-service/student/**, /api/thesis-service/admin/**, /api/thesis-service/student-period/**, /api/thesis-service/ai-chat/**, /internal/thesis/**, /internal/periods/**, /api/period-statistics/**

        - id: ${ASSIGN_SERVICE_NAME}
          uri: ${ASSIGN_SERVICE_URL}
          predicates:
            - Path=/api/assign-service/**, /internal/assignments/**

        - id: ${PROFILE_SERVICE_NAME}
          uri: ${PROFILE_SERVICE_URL}
          predicates:
            - Path=/api/profile-service/**, /internal/profiles/**

        - id: ${ACADEMIC_CONFIG_SERVICE_NAME}
          uri: ${ACADEMIC_CONFIG_SERVICE_URL}
          predicates:
            - Path=/api/academic-config-service/**, /internal/academic/**

        - id: ${EVAL_SERVICE_NAME}
          uri: ${EVAL_SERVICE_URL}
          predicates:
            - Path=/api/eval-service/admin/**, /api/eval-service/teacher/**, /api/eval-service/student/**, /internal/evaluations/**

        - id: ${SUBMISSION_SERVICE_NAME}
          uri: ${SUBMISSION_SERVICE_URL}
          predicates:
            - Path=/api/submission-service/**, /internal/submissions/**

        - id: ${COMMUNICATION_LOG_SERVICE_NAME}
          uri: ${COMMUNICATION_LOG_SERVICE_URL}
          predicates:
            - Path=/notifications/**, /chat/**, /api/communication-log-service/**, /api/communication-service/**

        - id: ${COMMUNICATION_LOG_SERVICE_NAME_WS}
          uri: ${COMMUNICATION_LOG_SERVICE_WS_URL}
          predicates:
            - Path=/ws/notifications/**, /ws/chat/**

eureka:
  instance:
    prefer-ip-address: ${EURKA_INSTANCE_PREFER_IP_ADDRESS}
    hostname: ${DOMAIN}
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: 8080
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web.socket: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
